// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:typed_data';

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// --------------------------------------------------------------------------
// FRB-generated Dart bindings for gui/rust/src/api.rs
//
// IMPORTANT: This file is a manually-written placeholder matching the Rust API
// signatures. It will be replaced by actual FRB codegen output when
// `flutter_rust_bridge_codegen generate` runs after the first successful
// C++ build of diffusion-rs-sys. The type shapes and function signatures
// match the Rust source exactly.
// --------------------------------------------------------------------------

/// Mirrors gui/rust/src/gui_params.rs GuiParams struct.
/// All fields are FRB-compatible primitives.
class GuiParams {
  final String preset;
  final String? weight;
  final String prompt;
  final String? negativePrompt;
  final int? steps;
  final int? width;
  final int? height;
  final int batchCount;
  final int seed;
  final String? cacheMode;
  final String previewMode;
  final String? upscaler;
  final double upscalerScale;
  final String? token;
  final bool lowVram;
  final String previewOutput;
  final String output;

  const GuiParams({
    required this.preset,
    this.weight,
    required this.prompt,
    this.negativePrompt,
    this.steps,
    this.width,
    this.height,
    required this.batchCount,
    required this.seed,
    this.cacheMode,
    required this.previewMode,
    this.upscaler,
    required this.upscalerScale,
    this.token,
    required this.lowVram,
    required this.previewOutput,
    required this.output,
  });
}

/// Mirrors gui/rust/src/api.rs GuiProgressEvent struct.
class GuiProgressEvent {
  final int step;
  final int steps;
  final double time;
  final Uint8List? previewImage;
  final Uint8List? finalImage;

  const GuiProgressEvent({
    required this.step,
    required this.steps,
    required this.time,
    this.previewImage,
    this.finalImage,
  });
}

/// Return the list of all available preset names.
/// FRB sync binding for gui/rust/src/api.rs::get_presets().
List<String> getPresets() =>
    RustLib.instance.api.crateApiGetPresets();

/// Return the valid weight variant names for a given preset.
/// FRB sync binding for gui/rust/src/api.rs::get_weights_for_preset().
List<String> getWeightsForPreset({required String preset}) =>
    RustLib.instance.api.crateApiGetWeightsForPreset(preset: preset);

/// Stream image generation progress events.
/// FRB stream binding for gui/rust/src/api.rs::generate_image_stream().
Stream<GuiProgressEvent> generateImageStream({required GuiParams params}) =>
    RustLib.instance.api.crateApiGenerateImageStream(params: params);

/// Initialize the Rust library.
/// FRB binding for gui/rust/src/lib.rs::init_app().
Future<void> initApp() => RustLib.instance.api.crateApiInitApp();
