// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'gui_params.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Return the list of all available preset names.
///
/// Uses `PresetDiscriminants::VARIANTS` from strum to stay in sync with the
/// Rust `Preset` enum automatically (FRB-01).
List<String> getPresets() => RustLib.instance.api.crateApiGetPresets();

/// Return the valid weight variant names for a given preset.
///
/// For presets without weight options, returns an empty vec.
/// Preset string is case-insensitive (FRB-02).
List<String> getWeightsForPreset({required String preset}) =>
    RustLib.instance.api.crateApiGetWeightsForPreset(preset: preset);

/// Stream image generation progress events to Dart.
///
/// Spawns a background thread that:
/// 1. Maps `GuiParams` to diffusion-rs `Config` + `ModelConfig` via `bridge::build_configs`
/// 2. Creates an `mpsc` channel and spawns a relay thread
/// 3. The relay thread reads each `Progress` event, reads preview PNG bytes from
///    disk (D-03: race accepted — `fs::read` failure yields `None`), and emits
///    a `GuiProgressEvent` through the `StreamSink`
/// 4. The main worker thread calls `gen_img_with_progress` (blocking)
/// 5. After generation, reads the final image bytes and emits a completion event
///
/// All work is wrapped in `catch_unwind` for defense-in-depth (D-07/FRB-06).
Stream<GuiProgressEvent> generateImageStream({required GuiParams params}) =>
    RustLib.instance.api.crateApiGenerateImageStream(params: params);

/// Progress event sent from Rust to Dart via StreamSink.
class GuiProgressEvent {
  /// Current inference step
  final int step;

  /// Total inference steps
  final int steps;

  /// Time elapsed for this step
  final double time;

  /// Preview image PNG bytes (None if file not yet available)
  final Uint8List? previewImage;

  /// Final image PNG bytes (populated only on the completion event)
  final Uint8List? finalImage;

  const GuiProgressEvent({
    required this.step,
    required this.steps,
    required this.time,
    this.previewImage,
    this.finalImage,
  });

  @override
  int get hashCode =>
      step.hashCode ^
      steps.hashCode ^
      time.hashCode ^
      previewImage.hashCode ^
      finalImage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiProgressEvent &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          steps == other.steps &&
          time == other.time &&
          previewImage == other.previewImage &&
          finalImage == other.finalImage;
}
