// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FRB-compatible DTO carrying all generation parameters across the FFI boundary.
/// All fields use primitive types only (String, i32, i64, f32, bool, Option<T>)
/// to satisfy flutter_rust_bridge serialization requirements (D-11 / FRB-04).
class GuiParams {
  /// Preset name (must match a PresetDiscriminants variant)
  final String preset;

  /// Weight type name (None for presets without weight variants)
  final String? weight;

  /// Text prompt for image generation
  final String prompt;

  /// Negative prompt (optional)
  final String? negativePrompt;

  /// Number of inference steps (None uses preset default)
  final int? steps;

  /// Image width (None uses preset default)
  final int? width;

  /// Image height (None uses preset default)
  final int? height;

  /// Number of images to generate in a batch
  final int batchCount;

  /// RNG seed (-1 for random)
  final PlatformInt64 seed;

  /// Cache acceleration mode name (None for no caching)
  final String? cacheMode;

  /// Preview mode: "None", "Fast", or "Accurate"
  final String previewMode;

  /// Upscaler mode name (None for no upscaling)
  final String? upscaler;

  /// Upscaler scale factor
  final double upscalerScale;

  /// HuggingFace API token (optional)
  final String? token;

  /// Enable low-VRAM optimizations (vae_tiling + flash_attention)
  final bool lowVram;

  /// Temp directory path for preview PNG written by the C callback
  final String previewOutput;

  /// Output path for the final generated image
  final String output;

  const GuiParams({
    required this.preset,
    this.weight,
    required this.prompt,
    this.negativePrompt,
    this.steps,
    this.width,
    this.height,
    required this.batchCount,
    required this.seed,
    this.cacheMode,
    required this.previewMode,
    this.upscaler,
    required this.upscalerScale,
    this.token,
    required this.lowVram,
    required this.previewOutput,
    required this.output,
  });

  @override
  int get hashCode =>
      preset.hashCode ^
      weight.hashCode ^
      prompt.hashCode ^
      negativePrompt.hashCode ^
      steps.hashCode ^
      width.hashCode ^
      height.hashCode ^
      batchCount.hashCode ^
      seed.hashCode ^
      cacheMode.hashCode ^
      previewMode.hashCode ^
      upscaler.hashCode ^
      upscalerScale.hashCode ^
      token.hashCode ^
      lowVram.hashCode ^
      previewOutput.hashCode ^
      output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiParams &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          weight == other.weight &&
          prompt == other.prompt &&
          negativePrompt == other.negativePrompt &&
          steps == other.steps &&
          width == other.width &&
          height == other.height &&
          batchCount == other.batchCount &&
          seed == other.seed &&
          cacheMode == other.cacheMode &&
          previewMode == other.previewMode &&
          upscaler == other.upscaler &&
          upscalerScale == other.upscalerScale &&
          token == other.token &&
          lowVram == other.lowVram &&
          previewOutput == other.previewOutput &&
          output == other.output;
}
