name: Release Plz

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - name: Dependencies
        run: sudo apt update && sudo apt install -y clang cmake
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Count sys files
        run: cargo package --allow-dirty -p diffusion-rs-sys
      - name: List sys files
        run: cargo package --allow-dirty -p diffusion-rs-sys -l
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}